### ISSUE TITLE
App crashes on detection

### ISSUE THREAD

**Issue by gptom** [LocalJoost/BlogComments#418]
Hi Joost.
First off: Thank you for sharing this little project with the community. I've been trying to positon an object ion a QR-code with a 2019 version of Unity.
I downloaded both your projects, the original and the improved one and they both show the same behaviour:
all compiles fine, app starts on the Hololens2, displays the both blue panels, but as soon as a QR-code is detected, I get a break-error in Visual Studio. No plane or anything is displayed and when I click "continue" in VS, the two blue panels appear again app will continue running but whenever a QR-code comes into view, it crashes again.

In the log below you can see that the app actually correctly identifies the QR-code, but then somehow fails while positioning.
Can you see from the log where the problem could be?

----------last part of Debug log ----------------------
`Found QR code A Test QR Code
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
MRTKExtensions.QRCodes.QRCodeTrackingService:SendProgressMessage(String)
MRTKExtensions.QRCodes.QRCodeTrackingService:QRCodeWatcher_Updated(Object, QRCodeUpdatedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
WinRT.EventSource`3:Invoke(IntPtr, IntPtr)
WinRT._Invoke:Invoke(IntPtr, IntPtr)
WinRT.<>c__DisplayClass1_0:<_invoke>b__0(_Invoke)
System.Action`1:Invoke(T)
WinRT.Delegate:MarshalInvoke(IntPtr, Action`1)
WinRT.EventSource:_invoke(IntPtr, IntPtr, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Ausnahme ausgelöst bei 0x00007FFEDF425E5C in QRCodeService.exe: Microsoft C++-Ausnahme: Il2CppExceptionWrapper bei Speicherort 0x000000B980C3C4D0.
Ausnahme ausgelöst bei 0x00007FFEDF425E5C in QRCodeService.exe: Microsoft C++-Ausnahme: Il2CppExceptionWrapper bei Speicherort 0x000000B980C3F120.
Ausnahme ausgelöst bei 0x00007FFEDF425E5C (KernelBase.dll) in QRCodeService.exe: WinRT originate error - 0x80004003 : 'Invalid pointer'.
Ausnahme ausgelöst bei 0x00007FFEDF425E5C in QRCodeService.exe: Microsoft C++-Ausnahme: winrt::hresult_error bei Speicherort 0x000000B980C3F4C0.

Das Programm "[1824] QRCodeService.exe" wurde mit Code 0 (0x0) beendet.
`

**Comment by LocalJoost** [comment]
Gutenmorgen ;)

Thank you for your compliments.
Unfortunately you have opened a _new issue_ in my blog comments project, in stead of commenting on the issue I make for every blog post, or opened an issue on the github project yourself, so I have not way to determine which of the branches in my project was your starting point. Please read this paragraph on this article. I can only get the code to run deployed and running on a HoloLens, not starting from Visual Studio, only with build Master, etc. There's a whole laundry list https://localjoost.github.io/Positioning-QR-codes-in-space-with-HoloLens-2-building-a-'poor-man's-Vuforia'/#conclusion
If you are using OpenXR, please read this too. https://localjoost.github.io/Upgrading-reading-and-positioning-QR-codes-with-HoloLens-2-to-Unity-2020-+-OpenXR-plugin/

Good luck! I can assure you it works. If you look in the comments and in the comments on the projects yourself, you see countless people having problems, but they all turned out to have deviated from my prescriptions at one point. The HoloLens QR tracking  works great, but it's finicky. You have to follow the rules. To the letter ;)

**Comment by gptom** [comment]
Hi Joost.
Thanks for the quick reply. This is actually my first time posting anything on github, so I might have picked the wrong way of positng something.
First, I will recheck everything. I did read the other posts and I saw that nearly everybody did something different from what you wrote.
I stuck to your description letter by letter: unity version, VS-versions, deployment version. I downloaded your Unity porject and didn't change anything. Just checked alle the settings and hit "build". 
I'm not using OpenXR, because in the "XR-Plug-in Management" in project settings there was nothing installed. I installed it now (unity said it has to remove the original internel XR-management first) Maybe that was the issue.
If I still can't get it to run by tonight, I might post another "initial issue" in the correct channel.
Cheers!
Thomas

**Comment by LocalJoost** [comment]
Good, well then you at least learned something about Github already. Good luck with checking out. One tip already : don't start the app from Visual Studio, deploy it to your HoloLens, then start it from the all apps menu. It's useless to start the C++ app from VS, it only causes problems and confusion

**Comment by gptom** [comment]
You were right: it WAS a blunder on miy side. I had VS on debug and release. As soon as I put it on "master" all worked fine. I saw "Release" in your Unity screenshot and didn't read the "master"-part in your text.
Sorry for wasting your time. ;)
Cheers!
Thomas

**Comment by LocalJoost** [comment]
Kein Problem! I am glad you got unstuck and learned a few things too. Good luck with whatever you are building - I hope I will see the results one day. :)
