### ISSUE TITLE
Comments on "'Upgrading to MRTK3 GA from a pre-release: some assembly required'"

### ISSUE THREAD

**Issue by LocalJoost** [LocalJoost/BlogComments#454]
Original article: https://localjoost.github.io/Upgrading-to-MRTK3-GA-from-a-pre-release-some-assembly-required/

**Comment by StrPython** [comment]
Hi! I'm currently experiencing performance issues while deploying my app to Hololens 2. I'm using MRTK3 pre-release, and I'm wondering if upgrading to MRTK3 GA would solve the problem. In my scene, I've loaded some 3D models with animations that I downloaded from Sketchfab, and I'm using ARMeshRenderer for spatial mapping. To check the frame rate, I've added SimpleProfiler, and unfortunately, the frame rate on Hololens 2 ranges from 12 to 30, and some models show a frame rate of below 10, which is unacceptable. Have you ever encountered this issue while developing for Hololens 2? When moving the body left and right on the HoloATC app on Hololens 2, the plane model appears distorted. Will you fix this issue?

**Comment by LocalJoost** [comment]
Absolutely. This most likely means your model is way too detailed, i.e. has too many polygons. HoloLens is an awesome device but it doesn't have a gaming class GPU. By design, otherwise its battery life would be measured in mere minutes 😁. So you will need to use a different model, or possibly reduce polygon count in Blender https://localjoost.github.io/Some-Blender-tricks-for-the-impatient-Mixed-Reality-HoloLens-developer-(2)/

**Comment by XRWebland** [comment]
so I ended up doing the exact same process and we decided to finally upgrade to general release a stable app we had that has gotten fairly complicated. I am running into the same issue with the poke interactor including from the input simulator where I roll over it with my mouse and it doesn't fire off the roll over state. The button is still clickable I just don't see the visuals and if I do the far ray everything works as expected. I tried updating the settings as suggested but no luck. " Far interaction - with a hand ray - fine, but the poke pointer - the circle that appears on your index finger - did not appear, and I could not press buttons. I noticed one of the asset files had changed. I reverted it, rebuilt the app, and then my problem was solved. The issue only is - I don’t quite remember which asset file. I seem to recall it was OpenXR Package Settings.asset (that sits in Assets\XR\Settings), but I am not sure."  I'm currently at this stage "At that time, I was a bit stressed because it seemed I was going to have defeat snatched from the jaws of victory." anyone have any ideas for how to fix this?

**Comment by LocalJoost** [comment]
Suggestion: build a new empty project, commit, copy assets from failed upgrade and see what happens? Gets anything overwritten? Maybe that will give you a clue

**Comment by Methalene** [comment]
So , I did as you explained in your Post but still after the updating the packages I am facing the error with GUID , what can i do to minimize these errors.

**Comment by LocalJoost** [comment]
@Methalene I am sorry, you have to be more specific with that. What is exactly your problem? Can you post a screenshot or something
